language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get update -qq;
      sudo apt-get install -y --no-install-recommends libsdl2-dev;
      sudo apt-get install libgtk-3-dev;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update;
      brew install sdl2;
    fi

before_script:
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j $CPU_NUM
  - make test
