language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "lrBx2iU41KcsTYmtk6bBaUt9i8gL9CojWY2wSLU3WKAzOq0WiLiATsd/pJEeUcUifBlIPLuvfpXGKVngUH+fWfm+yj7P2A3MQgZdW1QWhz1o0YNfigZIPSNXxYxcw5HuWVZVn0hyFkeKRhC99pOJeVSpKjFyEbr6PR5HagLytnzAKq7rHnyavgx6QGQddv2Vol3epE8239oIbBu9oheEAp7tcPeiGSB0WDeJaBI5fU7NkH0e1VCBINRSNCrj5NiGvhKlChc0netpiuZYUpS9mVUbXTsbaeA3dwvdO9SrnL+jHqhRs1Hi/TUiRCXLkCs71QVKwDZEa+ANidDpWoOarKMdCch3w003X8091hlgD2WC7VqI+eWXf9QavZojbVXmbZ5NemXpUYt3rz6chEIjRyy5k3JSg6Q8/7xHesmNJuTkMQjJBqY3a6T5ydRfJiIX+nEQ1GUZ1fdFIKMOYa4ygp7UalixJG0jDWi1hOetSPHIT4Mk8VZkfNoLxo/3vKPQ/RzMisKy+taYMpvqFDrqs/nod9UnADlUEacWAhgtfzKJEyHGiObj3Ncj1A6IOHTHZ+9T/ZOH3kEZ8QRh1MluIGr6Zk4M1cM3v/Z69f2Q2+OywEJKbtdpoCYIKR7/wXRCtQR/V2swsgQfWlG8P9HaONMbhh8dk0tlKRD69dPwiik="

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then 
      sudo apt-get update -qq;
      sudo apt-get install -y --no-install-recommends libsdl2-dev;
    fi
  - if [ $TRAVIS_OS_NAME == osx ]; then 
      brew update;
      brew install sdl2;
    fi

addons:
  coverity_scan:
    project:
      name: reicrof/hop
      description: HOP

    notification_email: c.l.forcier@gmail.com
    build_command_prepend:
    build_command: make
    branch_pattern: coverity_scan
  script:
    - echo -n | openssl s_client -CApath /etc/ssl/certs -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

before_script:
  - mkdir release
  - cd release
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make -j $CPU_NUM
  - ./tests/Tsc_test